name: multi-dic
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - cmake
  - ninja
  - pybind11
  - cxx-compiler
  - opencv
  - matplotlib
  - pyyaml
  - numpy
  - scipy
  - setuptools
  - wheel
  - pip:
      - scikit-build-core>=0.10
