name: multi-dic
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - cmake
  - ninja
  - pybind11
  - cxx-compiler
  - boost-cpp
  - eigen
  - ceres-solver
  - flann
  - openimageio
  - opencv
  - matplotlib
  - pyyaml
  - numpy
  - scipy
  - sqlite
  - gflags
  - glog
  - metis
  - suitesparse
  - glew
  - qt-main
  - setuptools
  - wheel
  - pip:
      - scikit-build-core>=0.10
